### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by Alexey1100** [t3hk0d3/smpp-protocol#1]
Hi. There is no such gem in rubygems repo.

``` bash
$ gem install smpp-protocol
ERROR:  Could not find a valid gem 'smpp-protocol' (>= 0) in any repository
```

Also

``` ruby
# Gemfile
gem 'smpp-protocol', git: 'https://github.com/t3hk0d3/smpp-protocol.git'
```

``` ruby
# test.rb
require 'smpp/protocol'
...
```

Gives:

``` bash
$ bundle && ruby test.rb
Using smpp-protocol 0.1.0 from https://github.com/t3hk0d3/smpp-protocol.git (at master@c164495)
Using bundler 1.12.5
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
/usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- smpp/protocol (LoadError)
    from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from test.rb:1:in `<main>'

```

**Comment by t3hk0d3** [comment]
@Alexey1100 
Its not published yet - Work in progress.
Currently gem is not useable. Lots and lots of things not done yet.

I'll update README and add TODO.

For second case - use `bundler exec`.

```
$ bundle
Fetching https://github.com/t3hk0d3/smpp-protocol.git
Resolving dependencies...
Using smpp-protocol 0.1.0 from https://github.com/t3hk0d3/smpp-protocol.git (at master@c164495)
Using bundler 1.12.4
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
$ echo "require 'smpp/protocol'; puts 'OK'" > test.rb
$ ruby test.rb
/Users/blahblah/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- smpp/protocol (LoadError)
    from /Users/blahblah/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from test.rb:1:in `<main>'
$ bundle exec ruby test.rb
OK
```
